app:
  build: .
  working_dir: /app
  volumes:
  - ./:/app
  ports:
  - "8000:8000"
  expose:
  - 9000
  links:
  - db
db:
 image: mysql:5.7
 volumes:
 - /var/lib/mysql
 ports:
 - "3309:3306"
 environment:
   MYSQL_ROOT_PASSWORD: 111111
   MYSQL_DATABASE: sblog
   MYSQL_USER: root
   MYSQL_PASSWORD: 111111